### PR TITLE
Add routes variable

### PR DESCRIPTION
**Pull request by micalgenus**

### CODE REVIEW

**Comment by blackcowmooo** [comment]
Argo sync fail

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-gateway-dev.micalgenus.com/pr\/6)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-gateway-dev.micalgenus.com/pr\/6)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-gateway-dev.micalgenus.com/pr\/6)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-gateway-dev.micalgenus.com/pr\/6)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-gateway-dev.micalgenus.com/pr\/6)

**Comment by blackcowmooo** [comment]
deploy success [url](http://moomark-gateway-dev.micalgenus.com/pr\/6)

**Review by lcc3108 — APPROVED** [review]

**Pull request merged**
